services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: gn-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GO_GN_FARM
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - gn-network

  # NestJS Application
  app:
    build: .
    container_name: gn-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: GO_GN_FARM
      JWT_SECRET: your-secret-key
      PORT: 8080
    depends_on:
      - db
    networks:
      - gn-network

# Docker volumes
volumes:
  postgres_data:

# Docker networks
networks:
  gn-network:
    driver: bridge