#####################################################################
# CẤU HÌNH DEVELOPMENT ENVIRONMENT - GN FARM GO SERVER
# File này chứa cấu hình cho môi trường phát triển local
# Các settings được tối ưu cho debugging và development
# Tác giả: GN Farm Development Team
# Phiên bản: 1.0
#####################################################################

# ===== CẤU HÌNH HTTP SERVER =====
# Thiết lập cho Gin web framework trong môi trường development
server:
  port: 8082 # Cổng chạy server (8082 cho dev)
  mode: dev # Chế độ Gin: dev/debug cho development

# ===== CẤU HÌNH POSTGRESQL DATABASE =====
# Cơ sở dữ liệu chính lưu trữ tất cả business data
postgres:
  host: localhost # Host database (localhost cho dev)
  port: 5432 # Cổng PostgreSQL standard
  username: postgres # Username kết nối database
  password: postgres # Password database (development)
  dbname: GO_GN_FARM # Tên database chính
  maxIdleConns: 10 # Số connection idle tối đa trong pool
  maxOpenConns: 100 # Số connection mở tối đa đồng thời
  connMaxLifetime: 3600 # Thời gian sống tối đa của connection (giây)

# ===== CẤU HÌNH REDIS CACHE =====
# Redis được sử dụng cho caching, session, rate limiting
redis:
  host: localhost # Host Redis server (127.0.0.1)
  port: 6379 # Cổng Redis standard
  password: # Mật khẩu Redis (không có trong dev)
  db: 0 # Database index (0 = default database)
  pool_size: 10 # Kích thước connection pool tối đa

# ===== CẤU HÌNH LOGGING =====
# Thiết lập ghi log chi tiết cho development và debugging
logger:
  log_level: debug # Mức độ log chi tiết (debug/info/warn/error)
  file_log_name: "./storages/logs/dev.001.log" # Đường dẫn file log
  max_size: 500 # Kích thước tối đa file log (MB)
  max_backups: 3 # Số file backup log giữ lại
  max_age: 28 # Số ngày giữ log cũ
  compress: true # Nén file log cũ để tiết kiệm dung lượng

# ===== CẤU HÌNH JWT AUTHENTICATION =====
# JSON Web Token cho xác thực và phân quyền người dùng
jwt:
  TOKEN_HOUR_LIFESPAN: 1 # Thời gian sống token (giờ)
  JWT_EXPIRATION: 1h # Chuỗi thời gian hết hạn JWT
  API_SECRET_KEY: "xxx.yyy.zzz" # Secret key ký JWT (đổi trong production)
