#####################################################################
# CẤU HÌNH PRODUCTION ENVIRONMENT - GN FARM GO SERVER
# File này chứa cấu hình cho môi trường production thật
# Các giá trị thực tế sẽ được đọc từ environment variables
# hoặc được override bởi deployment system (Docker, K8s)
#
# Tác giả: GN Farm Development Team
# Phiên bản: 1.0
#
# Lưu ý:
# - Không hard-code thông tin nhạy cảm trong file này
# - Sử dụng environment variables cho tất cả secrets
# - Cấu hình được tối ưu cho performance và bảo mật
# - Monitor và logging được kích hoạt đầy đủ
#####################################################################

# File này hiện tại đang trống
# Các cấu hình production thực tế sẽ được inject qua:
# 1. Environment variables từ Docker/Kubernetes
# 2. ConfigMaps và Secrets trong K8s
# 3. External configuration management tools
# 4. Cloud provider configuration services

# Mẫu cấu hình production (sử dụng env vars):
# server:
#   port: ${SERVER_PORT:-8082}
#   mode: ${GIN_MODE:-release}
# postgres:
#   host: ${DB_HOST}
#   port: ${DB_PORT:-5432}
#   username: ${DB_USER}
#   password: ${DB_PASSWORD}  # Đọc từ secret
#   dbname: ${DB_NAME}
# redis:
#   host: ${REDIS_HOST}
#   port: ${REDIS_PORT:-6379}
#   password: ${REDIS_PASSWORD}  # Đọc từ secret
